POST http://localhost:8080/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&code={{code}}&client_id=client&client_secret=secret&redirect_uri=https://oidcdebugger.com/debug

